import { chromium } from 'playwright-core';
import { mkdirSync } from 'node:fs';
const OUT = process.env.OUT ?? './shots';
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: 'dark' });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console: ${m.text()}`); });
await page.goto('http://localhost:4173/');
await page.click('text=Both');
await page.click('text=Set up camp');
await page.waitForSelector('text=Rings');
await page.evaluate(() => window.scrollBy(0, 420));
await page.waitForTimeout(200);
await page.screenshot({ path: `${OUT}/n1-today.png` });
await page.click('button:has-text("Preview") >> nth=1');
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/n2-preview.png` });
await page.click('.sheet button:has-text("Start")');
await page.waitForSelector('.player');
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/n3-player.png` });
await page.click('button[aria-label="Exit workout"]');
await page.click('text=Discard workout');
await page.waitForSelector('text=Rings');
await page.click('a[aria-label="Profile"]');
await page.waitForTimeout(300);
await page.evaluate(() => window.scrollBy(0, 700));
await page.waitForTimeout(200);
await page.screenshot({ path: `${OUT}/n4-profile.png` });
console.log(errors.length ? errors.join('\n') : 'no errors');
await browser.close();
